-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 17:20:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CeuEscuroDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CeuEscuroDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CeuEscuroDB` DEFAULT CHARACTER SET utf8 ;
USE `CeuEscuroDB` ;

-- -----------------------------------------------------
-- Table `CeuEscuroDB`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuEscuroDB`.`TipoUsuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuEscuroDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuEscuroDB`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Senha` CHAR(6) NOT NULL,
  `DataNascUsuario` DATE NOT NULL,
  `TipoUsuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Usuario_TipoUsuario_idx` (`TipoUsuario_Id` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`TipoUsuario_Id`)
    REFERENCES `CeuEscuroDB`.`TipoUsuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuEscuroDB`.`Classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuEscuroDB`.`Classificacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `(DescricaoClassificacao)` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuEscuroDB`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuEscuroDB`.`Genero` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuEscuroDB`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuEscuroDB`.`Filme` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(150) NOT NULL,
  `Produtora` VARCHAR(150) NOT NULL,
  `UrlImg` VARCHAR(250) NOT NULL,
  `Classificacao_Id` INT NOT NULL,
  `Genero_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Filme_Classificacao1_idx` (`Classificacao_Id` ASC),
  INDEX `fk_Filme_Genero1_idx` (`Genero_Id` ASC),
  CONSTRAINT `fk_Filme_Classificacao1`
    FOREIGN KEY (`Classificacao_Id`)
    REFERENCES `CeuEscuroDB`.`Classificacao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filme_Genero1`
    FOREIGN KEY (`Genero_Id`)
    REFERENCES `CeuEscuroDB`.`Genero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
